INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:22:33] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:22:57] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:23:54] "[33mGET /Clase2Flask/rutas/persona/static/favicon.ico?v=2 HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:23:58] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:25:09] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:25:09] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:25:09] "[33mGET /static/favicon.ico?v=2 HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:25:21] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:25:21] "[33mGET /static/favicon.ico?v=2 HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:28:37] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:28:37] "[33mGET /static/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:28:58] "[33mGET /static/ HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:28:58] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:29:48] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:29:52] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:29:52] "[33mGET /static/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:35:48] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:35:48] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:36:06] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:36:06] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:43:45] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:43:45] "[33mGET /static/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:44:53] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:44:56] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:44:57] "[33mGET /static/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:49:16] "[33mGET /static/FotoCyber.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:49:17] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:51:55] "[33mGET /static/FotoCyber.png HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 22:51:57] "[33mGET /static/FotoCyber HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:01:29] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:01:33] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:01:34] "[33mGET /static/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:07:01] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:07:09] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:24:08] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:24:08] "[33mGET /FotoCyber.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:24:46] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:24:46] "[33mGET /FotoCyber.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:30:18] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:30:38] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:30:38] "[33mGET /static/FotoCyber.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\persona\personas.py", line 15, in inicial
    return render_template('index.html',personas=personas)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\persona\templates\index.html", line 45, in top-level template code
    <h3>Foto Logo</h3><img src="{{ url_for('appPersona.static', filename='FotoCyber.jpg') }}" alt="Mike" height="240px" width="300px">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\routing\map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'appPersona.static' with values ['filename']. Did you mean 'apppersona.static' instead?
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:31:45] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:31:46] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:33:00] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 23:33:00] "[33mGET /static/FotoCyber.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 08:11:38] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 08:11:38] "[33mGET /static/FotoCyber.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 08:11:39] "[33mGET /static/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:05:29] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:05:29] "[33mGET /static/FotoCyber.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:05:30] "[33mGET /static/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:05:34] "GET /agregar HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:05:34] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:05:53] "[32mPOST /agregar HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:05:53] "GET /index HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:05:53] "[33mGET /static/FotoCyber.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:11:32] "GET /index HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:11:32] "[33mGET /static/FotoCyber.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:21:47] "GET /index HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:21:47] "[33mGET /static/FotoCyber.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:23:13] "[31m[1mGET /producto/agregar HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:23:30] "[31m[1mGET /producto/agregar HTTP/1.1[0m" 405 -
ERROR:app:Exception on /producto/agregar [POST]
Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\producto\producto.py", line 10, in agregarProducto
    json = request.get_json()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\producto\producto.py", line 19, in agregarProducto
    return jsonify({"status":400,"mensaje":ex})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UnsupportedMediaType is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:23:47] "[35m[1mPOST /producto/agregar HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:25:39] "POST /producto/agregar HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:39:05] "[31m[1mGET /producto/obtener HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:39:11] "[31m[1mGET /producto/obtener HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:39:51] "POST /producto/agregar HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:41:13] "[31m[1mGET /producto/editar HTTP/1.1[0m" 405 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:56:01] "[33mGET /indexImagen HTTP/1.1[0m" 404 -
ERROR:app:Exception on /leerImagen [GET]
Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\imagen\imagen.py", line 30, in indexImagen
    return render_template('mostrarImagen.html')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: mostrarImagen.html
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 09:56:14] "[35m[1mGET /leerImagen HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 11:22:58] "GET /index HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 11:22:59] "[33mGET /static/FotoCyber.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 11:23:03] "GET /agregar HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 11:24:51] "GET /agregar HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /producto/editar [POST]
Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\producto\producto.py", line 24, in editarProducto
    json = request.get_json()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\producto\producto.py", line 32, in editarProducto
    return jsonify({"status":400,"mensaje":ex})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UnsupportedMediaType is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 11:36:29] "[35m[1mPOST /producto/editar HTTP/1.1[0m" 500 -
ERROR:app:Exception on /producto/editar [POST]
Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\producto\producto.py", line 24, in editarProducto
    json = request.get_json()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\producto\producto.py", line 32, in editarProducto
    return jsonify({"status":400,"mensaje":ex})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type UnsupportedMediaType is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 11:37:16] "[35m[1mPOST /producto/editar HTTP/1.1[0m" 500 -
ERROR:app:Exception on /producto/editar [POST]
Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\wrappers\request.py", line 611, in get_json
    rv = self.json_module.loads(data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 188, in loads
    return json.loads(s, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 2 column 10 (char 12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\wrappers\request.py", line 645, in on_json_loading_failed
    raise BadRequest(f"Failed to decode JSON object: {e}")
werkzeug.exceptions.BadRequest: 400 Bad Request: Failed to decode JSON object: Expecting ':' delimiter: line 2 column 10 (char 12)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\producto\producto.py", line 24, in editarProducto
    json = request.get_json()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\wrappers\request.py", line 620, in get_json
    rv = self.on_json_loading_failed(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\wrappers.py", line 135, in on_json_loading_failed
    raise BadRequest() from e
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\producto\producto.py", line 32, in editarProducto
    return jsonify({"status":400,"mensaje":ex})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type BadRequest is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 11:38:10] "[35m[1mPOST /producto/editar HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /producto/editar [POST]
Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\wrappers\request.py", line 611, in get_json
    rv = self.json_module.loads(data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 188, in loads
    return json.loads(s, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 2 column 10 (char 12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\wrappers\request.py", line 645, in on_json_loading_failed
    raise BadRequest(f"Failed to decode JSON object: {e}")
werkzeug.exceptions.BadRequest: 400 Bad Request: Failed to decode JSON object: Expecting ':' delimiter: line 2 column 10 (char 12)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\producto\producto.py", line 24, in editarProducto
    json = request.get_json()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\wrappers\request.py", line 620, in get_json
    rv = self.on_json_loading_failed(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\wrappers.py", line 135, in on_json_loading_failed
    raise BadRequest() from e
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\producto\producto.py", line 32, in editarProducto
    return jsonify({"status":400,"mensaje":ex})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type BadRequest is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 11:38:29] "[35m[1mPOST /producto/editar HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 11:38:40] "POST /producto/editar HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 11:50:11] "POST /producto/eliminar HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 11:52:51] "POST /producto/obtener HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /leerImagen [GET]
Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\imagen\imagen.py", line 30, in indexImagen
    return render_template('mostrarImagen.html')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: mostrarImagen.html
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 12:01:27] "[35m[1mGET /leerImagen HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 12:03:41] "GET /leerImagen HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 12:06:36] "GET /leerImagen HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 12:07:30] "[31m[1mPOST /leerImagen HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [19/Oct/2023 12:07:30] "[31m[1mPOST /leerImagen HTTP/1.1[0m" 405 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [30/Oct/2023 21:29:26] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Oct/2023 21:29:27] "[33mGET /static/FotoCyber.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [30/Oct/2023 21:29:28] "[33mGET /static/favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [31/Oct/2023 09:02:34] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Oct/2023 09:02:34] "[33mGET /static/FotoCyber.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [31/Oct/2023 09:02:35] "[33mGET /static/favicon.ico HTTP/1.1[0m" 404 -
ERROR:flask_migrate:Error: Directory migrations already exists and is not empty
